{
 "title": "Triton Inference Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successful Inferences",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Failed Inferences",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nv_inference_request_failure", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "nv_inference_queue_duration_us", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Compute Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_compute_duration_us",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}