{
 "title": "Triton Inference Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successful Inference Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Failed Inference Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nv_inference_request_fail", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Queue Duration (µs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "nv_inference_queue_duration_us", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Compute Duration (µs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "nv_inference_compute_duration_us",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}